name: ej_workflow.yml
#Ejemplo de flujo de trabajo
on:
  workflow_dispatch:
  #push:
    #branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Imprimir la ruta del espacio de trabajo
        run: echo "El espacio de trabajo es:${{ env.GITHUB_WORKSPACE }}"
        #shell: bash  # Especifica el shell
      - name: Listar el contenido del directorio
        run: ls -l ${{env.GITHUB_WORKSPACE }}
        #shell: bash  # Especifica el shell
      - name: Imprimir el Shell
        run: echo  "El Sehll es:$HELL"
