name: Ejemplo de flujo de trabajo
on: 
  push:
    branches: [main]

jobs:
  build:

    runs-om: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Imprimir la ruta del espacio de trabajo
        run: echo "El espacio de trabajo es:" $ {{ env.GITHUB_WORKSPACE }}"
      - name: Listar el contenido del directorio
        run: ls $ {{env.GITHUB_WORKSPACE }}
