name: Test

on: [push]

jobs:
  test-build: 
    runs-on: ubuntu-latest
  # Como ejecutar comnados
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Listar ls -l
        run: ls -l

      - name: Setup Node.js environment #Configuración node
        uses: actions/setup-node@v4.0.4
        #with: #Error no se encuentra en el manifiesto 
         #node-version: lastest
      
      - name: Node version # Setea node
        run: node --version #Da la versión de node
      
      - name: PHP #Setear PHP
        uses: shivammathur/setup-php@v2
          #with: #Genera error de sintaxys
            #php-version: '8.3' 

          #with:   
            #php-version: "8.3" # No funciona
      - name: Version PHP
        run: php --version
     
