name: Test

on: [push]

jobs:
  test-build: 
    runs-on: ubuntu-latest
  # Como ejecutar comnados
    steps:
      - name: ls
        run: | # Pie permite generar string multilinea
          echo : "Hola Mundo desde main.yml" >> hola.txt
          cat hola.txt