name: Test compositive Actions

on: [push]

jobs:
  local-action: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      
      - name: Importar action - reusable
        uses: ./.github/actions/my-action
        with: #Pasar el parametro de la acción, inuts
          message: Fernando # El nombre de la variable y el valor 
