name: Test compositive Actions

on: [push]

jobs:
  local-action: 
    run-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      
      - name: Importar action - reusable
        uses: ./.github/actions/my-action
