name: Variables de entorno

on: [push]

jobs:
  hi-variablee:
    runs-on: ubuntu-latest 

    env:
      MY_VAR: 'Mi variable de entorno' #Se inyectan directamente en el servidor ubuntu-latests

    steps: 
    - name: Test_Variable
      run: echo "Valor: $$MY_VAR"