name: Llamado variable de entorno 

on: [push]

jobs:
  hi-varentor:
    runs-on: ubuntu-latest
    env: #Varialesd entorno 
          plataform: AWS
          region: us-east-1
          account: 1234567890
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}          

    steps:
      - name: "Mostrar saludo"
        run: echo "Hola Mundo desde LLamado de variable de entorn"
      
      - name: "Mostrando varbles de entorno"
        run:  | #Multiples lineas
          #echo "Valor de $plataform"
          echo "Valor de ${{ env.plataform }}"
          #echo "Región :$region"
          echo "Región :${{ env.region }}"
          #echo "Account :$account"
          echo "Account :${{ env.account}}"    
      - name: "Mostrar secretos de variales Repo"
        run: |
          echo "=== Aquí imprime los valores de los secretos de variables repos ==="
          echo "Este es el valor de username :${{ secrets.USERNAME }}"
          echo "Este es el valor de password :${{ secrets.PASSWORD }}"
          echo "===================================================================="
      
      - name: "Mostrar viriables de Repo"
        run: |
          echo "Variable de Repo Project_version:${{ vars.PROJECT_VERSION }}"

