name: Variable de entorno 

on: 
    [push]

jobs:
 hi-variables:
  runs-on: ubuntu-latest

  steps:
    - name: Test variable de entorno
      run: ec "Valor de la variable de entorno ${{ vars.MY_VARIABLE_2 }}"   
      #Variables de contexto, para llamar las variables de entorno se da uos del ojeto vars 