name: Hola MUNDO2

on: [push]

jobs: 
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Hola
      run: echo "Hola MUUNDO2"

  other: 
    runs-on: ubuntu-latest

    steps: 
      - name: LS
        run: echo "Hola MUNDO2 - test.yml"