name: Hola Mundo #Nombre de workflow

on:
  workflow_dispatch: 
  #[push] #Evento, se hace push a un al repo
  

jobs: #Ejecuta dentro de un servidor
  hola: 
    runs-on: ubuntu-latest #Directiva 
    steps: #Definir los Steps, que realza diferentes acciones, siendo esta la unidad mas peque. 
      - name: Hola Mundo #Nombre representativo
      - run: echo "Hola Mundo" #Directiva run que permite correr un comnando, run define la acción 
      