name: Hola MUNDO2

on:
  #push:
    workflow_dispatch:
    #branch: #Defino que este workflow se ejecute en esta lista de branch
     # - main
  # También funciona con PR
  # Este workflow se va a ejecutar cuando se haga push a la branch m ain
  # Como tambien se haga un PR a la rama main
  pull_request:
    branch:
      - main

jobs:  #Jobs
  hola:
    runs-on: ubuntu-latest

    steps: #Steps, pasos
    - name: Hola
      run: echo "Hola MUUNDO2"

    - name: touch file
      run: touch hola.txt
    
    - name: Set text
      run: echo "Hola Mundote" >> hola.txt
    
    - name: Read file
      run: cat hola.txt

  other: 
    runs-on: ubuntu-latest
    needs: hola #Directiva dependencia de ejecución, pasando el job que necesito que se ejecute y terrmine para proceder a ejecutar 
                # Tambien se puede definir como un arreglo [hola]    
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.1    
      - name: LS
        run: ls -al