name: Variable de entorno 

on: 
    [push]

jobs:
 hi-variables:
  runs-on: ubuntu-latest

  steps:
    - name: Test variable de entorno
      run: echo "Valor de la variable de entorno es :${{ vars.MY_VARIABLE_2 }}"   
      #Variables de contexto, para llamar las variables de entorno se da uos del ojeto vars 

    - name: Tes secreto de Repo *Secret*
      run: echo "El valor se secret del Repo :${{secrets.MY_SECRET}}" #Interpolación con el objeot secrets
      