name: Variables de entorno

on: [push]

jobs:
  hi-variablee:
    runs-on: ubuntu-latest 

    env:
      MY_VAR: 'Mi variable de entorno' #Se inyectan directamente en el servidor ubuntu-latests ,variable de entorno inyectada

    steps: 
    - name: Test_Variable
      #run: echo "El Valor es:$MY_VAR" # Accede correctamente a la variable de entorno,Contexto (GitHub Actions)
      #run: echo "Valor de la variable es :${{ env.MY_VAR }}" #Variable del shell (ejecutor)
      #1env: Se comentarea para ejercicio llaado de vairable de repositorio #1
        #1STEP_MY_VAR: Nivel Step
      #1run: echo "Valor variable a $STEP_MY_VAR"
      #run: echo "Valor variable entorno repo ${{ vars.MY_VARIABLE_2 }}" tst basico
      run: echi "valor variable de entonrno repo ${{ vars.ENV_CONTEXT_VAR }}"
      





