name: Llamado variable de entorno 

on: [push]

jobs:
  hi-varentor:
    runs-on: ubuntu-latest
    env: #Varialesd entorno 
          plataform: AWS
          region: us-east-1
          account: 1234567890

    steps:
      - name: "Mostrar saludo"
        run: echo "Hola Mundo desde LLamado de variable de entorn"
      
      - name: "Mostrando varbles de entorno"
        run:  | #Multiples lineas
          #echo "Valor de $plataform"
          echo "Valor de ${{ env.plataform }}"
          #echo "Región :$region"
          echo "Región :${{ env.region }}"
          #echo "Account :$account"
          echo "Account :${{ env.account}}"        