name: Hola MUNDO2

on: [push]

jobs:  #Jobs
  hola:
    runs-on: ubuntu-latest

    steps: #Steps, pasos
    - name: Hola
      run: echo "Hola MUUNDO2"

    - name: Touch file
      run: touch hola.txt
    
    - name: Set text
      run: echo "Hola Mundote" >> hola.txt
    
    - name: Read file
      run: cat hola.txt

  other: 
    runs-on: ubuntu-latest
    needs: hola #Directiva dependencia de ejecución, pasando el job que necesito que se ejecute y terrmine para proceder a ejecutar 
                # Tambien se puede definir como un arreglo [hola]    
    steps: 
      - name: LS
        run: ls -al