name: Variables de entorno

on: [push]

jobs:
  hi-variablee:
    runs-on: ubuntu-latest 

    env:
      MY_VAR: 'Mi variable de entorno' #Se inyectan directamente en el servidor ubuntu-latests

    steps: 
    - name: Test_Variable
      run: echo "El Valor es:$MY_VAR" # Accede correctamente a la variable de entorno,Contexto (GitHub Actions)
      #run: echo "Valor de la variable es :${{ env.MY_VAR }}" #Variable del shell (ejecutor)