name: Llamado variable de entorno 

on: [push]

jobs:
  hi-varentor:
    runs-on: ubuntu-latest

    steps:
      - name: Llamado de variables
      run: echo "Hola Mundo desde LLamado de variable de entorn"
